POST localhost:3001/api/trpc/subject.create
Content-Type: application/json

{
  "json": {
    "teacherId": "clanwixxv00002e6de9mciu9k",
    "title": "abc",
    "description": "def",
    "studyProgrammeId": "clanwixxv00002e6de9mciu9k"
  }
}
