name: "uu-bpmi"
services:
  posgresql:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "subjectMan"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
      - ".data/mariadb:/var/lib/postgres"